services:
  app: 
    build: .
    ports:
      - 7278:7278
    environment:
      ASPNETCORE_URLS: http://+:7278
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic MTQ4MTc5NzpnbGNfZXlKdklqb2lNVFl5T1RBNU15SXNJbTRpT2lKemRHRmpheTB4TkRneE56azNMVzkwYkhBdGQzSnBkR1V0ZEdsdFpTMXplVzVqSWl3aWF5STZJams0T1UwNVNuQTFOVVU1Y1dObVVscHFhREIxT1hSd055SXNJbTBpT25zaWNpSTZJbkJ5YjJRdFpYVXRkMlZ6ZEMweUluMTk="
